name: Plugin Go test
on:
  pull_request:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  go-test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: setup cluster
        uses: ./.github/workflows/cluster-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build the binary and run unit tests
        run: |
          make build
          sudo cp bin/kubectl-rook-ceph /usr/local/bin/kubectl-rook_ceph
          make test

      - name: Cluster Health
        run: |
          set -e
          kubectl rook-ceph health

      - name: Ceph status
        run: |
          set -ex
          kubectl rook-ceph ceph status

      - name: Mon restore
        env:
          ROOK_PLUGIN_SKIP_PROMPTS: true
        run: |
          set -ex
          # test the mon restore to restore to mon a, delete mons b and c, then add d and e
          kubectl rook-ceph  mons restore-quorum a
          kubectl  -n rook-ceph wait pod -l app=rook-ceph-mon-b --for=delete --timeout=90s
          kubectl -n rook-ceph wait pod -l app=rook-ceph-mon-c --for=delete --timeout=90s
          tests/github-action-helper.sh wait_for_three_mons rook-ceph
          kubectl -n rook-ceph wait deployment rook-ceph-mon-d --for condition=Available=True --timeout=90s
          kubectl -n rook-ceph wait deployment rook-ceph-mon-e --for condition=Available=True --timeout=90s

      - name: Rbd command
        run: |
          set -ex
          kubectl rook-ceph rbd ls replicapool

      - name: Get mon endpoints
        run: |
          set -ex
          kubectl rook-ceph mons

      - name: Update operator configmap
        run: |
          set -ex
          kubectl rook-ceph operator set ROOK_LOG_LEVEL DEBUG

      - name: Print cr status
        run: |
          set -ex
          kubectl rook-ceph rook version
          kubectl rook-ceph rook status
          kubectl rook-ceph rook status all
          kubectl rook-ceph rook status cephobjectstores

      - name: Restart operator pod
        run: |
          set -ex
          kubectl rook-ceph operator restart
          # let's wait for operator pod to be restart
          POD=$(kubectl -n rook-ceph get pod -l app=rook-ceph-operator -o jsonpath="{.items[0].metadata.name}")
          kubectl -n rook-ceph wait --for=delete pod/$POD --timeout=100s
          tests/github-action-helper.sh wait_for_operator_pod_to_be_ready_state_default

      - name: Debug Mode
        run: |
          set -ex
          kubectl rook_ceph debug start rook-ceph-osd-0
          tests/github-action-helper.sh wait_for_deployment_to_be_running rook-ceph-osd-0-debug rook-ceph

          kubectl rook_ceph debug stop rook-ceph-osd-0
          tests/github-action-helper.sh wait_for_deployment_to_be_running rook-ceph-osd-0 rook-ceph

      - name: Purge Osd
        run: |
          set -ex
          kubectl -n rook-ceph scale deployment rook-ceph-osd-0 --replicas 0
          kubectl rook-ceph rook purge-osd 0 --force

      - name: collect common logs
        if: always()
        uses: ./.github/workflows/collect-logs
        with:
          name: go-test

      - name: consider debugging
        if: failure()
        uses: mxschmitt/action-tmate@v3
